FORMAT: 1A
HOST:api.expensemanager.com/api/v1/users

# User

Api's to signup,signin,logout and delete account,
These apis are responsible for creating,updating,fetching and deleting devices 

## User Signup 

### Signup a user [Post]

You may signup to expense manager using this action.This take user and device information as follow
User - Name ,Email Address(optional),phone number,profileImageUrl (Optional),CoverImageUrl(Optional)
Device Detail - DeviceUUID,Platform,OsVersion,GCMToken(Optional)

+ Request (application/user)

    + Headers
            
            UserAgent: exmanager/Android/4.2
            
    
    + Body
        
            {
                    "User":
                        {
                             "UserName":"Subham Tyagi"
                             "EmailAddress":"Subham@gmail.com"
                             "PhoneNumber":"9663295153"
                             "ProfileImageUrl":"https://www.google/profilepic"
                             "CoverImageUrl":"https://www.google/coverImage"
                             "DeviceDetail":
                                {
                                    "DeviceUUID":"asdjaksjh1y239129839kajbdksjbdk"
                                    "Platform":"Android"/"IOS"/"Windows"
                                    "OsVersion":"4.4"
                                    "GCMToken":"akjdlakjsldsldjlaskjd"
                                }
                         
                        }
            }
        
+ Repsonse 200 (application/json)

    + Headers
                
                ContentType:application/json
    
    + Body
        
                {
                    "status":"success"
                    "data":
                        {
                            "message": "OTP send as sms/email on provided number/email"
                        }
                }
        
        
+ Reponse 419 (application/json)
    
    + Headers
            
                ContentType:application/json
    
    + Body
  
            {
                 "status":"fail"
                 "data":
                    {
                        "message": "User already register"
                    }
            
            }
        
+ Rsponse 400 (application/json)
    
    + Headers
                
                ContentType:application/json
                
    + Body
        
            {
                "status":"fail"
                    {
                        data:
                        [
                            {
                                "code":"1"
                                "message":"User name empty"
                            },
                            {
                                "code":"2"
                                "message":"Phone number empty"
                            },
                            {
                                "code":"1"
                                "message":"Device uuid empty"
                            },
                        ]
                        
                    }
            }
        

## User Login
### Login user into system [POST]

You may login to expense manager using this action. It takes a JSON
object containing a valid phone no or email id

+ Request (application/json)
    + Headers
                
                ContentType:application/json
                UserAgent: exmanager/Android/4.2
                
    + Body
    
            {
                "phoneNo":"1234567890"
            }

+ Response 200 (application/json)

    + Headers

            ContentType: application/json

    + Body

            {
                "status":"success:
                "data":
                    {
                        "message":"OTP has been send to registerd emailid/phone no"
                    }
            }
            
            
+ Response 404 (application/json)

    + Headers

            ContentType: application/json

    + Body

            {
                "status":"faile:
                "data":
                    {
                        "message":"User is not registerd."
                    }
            }
            
            

+ Response 400 (application/json)

    + Headers

            ContentType: application/json

    + Body

            {
                "status":"faile:
                "data":
                    {
                        "message":"Empty phone number"
                    }
            }